name: Update README
on: # 触发时机
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON,SAT,SUN" # 每周一，周六触发，也可以 0 0 * * 1,6
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Update README
        run: node index.js ${{ secrets.GIT_UPDATE_README_TOKEN }}

      - name: Show branch and remote
        run: |
          git branch
          git remote -v

      - name: Commit and push if changed # 将README.md更新到仓库
        run: |
          git config --global user.email "wangrongding@qq.com"
          git config --global user.name "wangrongding"
          git add .
          git commit -m "Updated Readme" || exit 
          git push

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.9
