name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 24 * * *"
  push:
    branches:
      - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Update README
        run: node index.js ${{ secrets.GIT_UPDATE_README_TOKEN }}

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.9
